version: 2

models:
  # Review JSON Normalization Models
  - name: int_review_persona_attributes
    description: "Normalized persona attributes from customer reviews - key input for gap analysis"
    columns:
      - name: review_id
        description: "References the original review"
        tests:
          - not_null
      - name: ad_account_id
        description: "Links to ad accounts for cross-source analysis"
        tests:
          - not_null
      - name: persona_attribute
        description: "Normalized persona attribute (e.g., 'busy professional', 'health-conscious')"
        tests:
          - not_null
      - name: confidence_score
        description: "AI confidence score for persona attribute extraction"
      - name: source_system
        description: "Always 'review' for this model"

  - name: int_review_value_propositions
    description: "Normalized value propositions from customer reviews"
    columns:
      - name: review_id
        description: "References the original review"
        tests:
          - not_null
      - name: value_proposition
        description: "Normalized value proposition mentioned in review"
        tests:
          - not_null
      - name: importance_score
        description: "Importance score for this value proposition"
      - name: sentiment
        description: "Sentiment associated with this value proposition"

  - name: int_review_problems
    description: "Normalized problems from customer reviews"
    columns:
      - name: review_id
        description: "References the original review"
        tests:
          - not_null
      - name: problem
        description: "Normalized problem mentioned in review"
        tests:
          - not_null
      - name: severity_score
        description: "Severity score for this problem"
      - name: problem_category
        description: "Category classification for the problem"

  - name: int_review_barriers
    description: "Normalized barriers from customer reviews"
    columns:
      - name: review_id
        description: "References the original review"
        tests:
          - not_null
      - name: barrier
        description: "Normalized barrier mentioned in review"
        tests:
          - not_null
      - name: impact_score
        description: "Impact score for this barrier"
      - name: barrier_type
        description: "Type classification for the barrier"

  # Ad JSON Normalization Models
  - name: int_ad_persona_attributes
    description: "Normalized persona attributes from ad creative analysis"
    columns:
      - name: ad_analysis_id
        description: "References the ad analysis"
        tests:
          - not_null
      - name: ads_meta_id
        description: "References ads meta for performance linking"
        tests:
          - not_null
      - name: ad_account_id
        description: "Links to ad accounts for cross-source analysis"
        tests:
          - not_null
      - name: persona_attribute
        description: "Normalized persona attribute targeted by ad"
        tests:
          - not_null
      - name: core_persona
        description: "Primary persona identified for this ad"
      - name: source_system
        description: "Always 'cad' for this model"

  - name: int_ad_value_propositions
    description: "Normalized value propositions from ad creative analysis"
    columns:
      - name: ad_analysis_id
        description: "References the ad analysis"
        tests:
          - not_null
      - name: value_proposition
        description: "Normalized value proposition promoted in ad"
        tests:
          - not_null
      - name: strength_score
        description: "Strength score for this value proposition in the ad"
      - name: clarity_score
        description: "Clarity score for this value proposition"

  - name: int_ad_problems
    description: "Normalized problems from ad creative analysis"
    columns:
      - name: ad_analysis_id
        description: "References the ad analysis"
        tests:
          - not_null
      - name: problem
        description: "Normalized problem addressed by ad"
        tests:
          - not_null
      - name: relevance_score
        description: "Relevance score for this problem"
      - name: urgency_score
        description: "Urgency score for this problem"

  - name: int_ad_barriers
    description: "Normalized barriers from ad creative analysis"
    columns:
      - name: ad_analysis_id
        description: "References the ad analysis"
        tests:
          - not_null
      - name: barrier
        description: "Normalized barrier addressed by ad"
        tests:
          - not_null
      - name: solution_strength
        description: "Strength of the solution provided for this barrier"
      - name: addressability_score
        description: "How well the ad addresses this barrier"

  # Unified and Analysis Models
  - name: int_unified_persona_attributes
    description: "Unified view of persona attributes from both reviews and ads with coverage analysis"
    columns:
      - name: ad_account_id
        description: "Account identifier for analysis"
        tests:
          - not_null
      - name: persona_attribute
        description: "Normalized persona attribute"
        tests:
          - not_null
      - name: source_system
        description: "Either 'review' or 'cad'"
        tests:
          - not_null
      - name: coverage_type
        description: "Whether persona appears in 'both', 'review_only', or 'ad_only'"
        tests:
          - not_null
          - accepted_values:
              values: ['both', 'review_only', 'ad_only']
      - name: total_review_mentions
        description: "Total mentions in reviews"
      - name: total_ad_mentions
        description: "Total mentions in ads"

  - name: int_cross_account_persona_mapping
    description: "ENHANCED: Maps personas between CAD and Review accounts using DWH mapping table - KEY FOR CROSS-SYSTEM ANALYSIS"
    columns:
      - name: cad_account_id
        description: "CAD account ID from mapping table"
        tests:
          - not_null
      - name: review_account_id
        description: "Review account ID from mapping table"
      - name: persona_attribute
        description: "Normalized persona attribute found in both systems"
        tests:
          - not_null
      - name: persona_coverage
        description: "Coverage type: 'found_in_both', 'cad_only', 'review_only', 'review_only_unmapped'"
        tests:
          - not_null
      - name: cad_persona_mentions
        description: "Number of times persona mentioned in CAD ads"
      - name: review_persona_mentions
        description: "Number of times persona mentioned in reviews"
      - name: cross_system_alignment_score
        description: "Score indicating alignment between CAD and Review mentions of this persona"
      - name: cad_account_name
        description: "CAD account name from mapping"
      - name: review_account_name
        description: "Review account name from mapping"

  - name: int_persona_performance_scorecard
    description: "ENHANCED: Performance scorecard with cross-account mapping and boosted opportunity scoring - KEY MODEL FOR ANALYSIS"
    columns:
      - name: ad_account_id
        description: "Account identifier for analysis"
        tests:
          - not_null
      - name: persona_attribute
        description: "Normalized persona attribute"
        tests:
          - not_null
      - name: performance_tier
        description: "Performance tier (top_performer, strong_performer, moderate_performer, weak_performer, poor_performer)"
        tests:
          - not_null
      - name: avg_roas
        description: "Average ROAS for ads targeting this persona"
      - name: avg_ctr
        description: "Average CTR for ads targeting this persona"
      - name: total_spend
        description: "Total spend on ads targeting this persona"
      - name: composite_performance_score
        description: "Weighted composite performance score"
      - name: gap_analysis_category
        description: "Gap analysis category (underperforming_persona, well_served_persona, opportunity_persona, unaddressed_persona)"
      - name: opportunity_score
        description: "ENHANCED: Opportunity score with cross-account boost (higher = better opportunity)"
      - name: review_mention_count
        description: "Number of times this persona is mentioned in reviews"
      - name: persona_coverage
        description: "Cross-system persona coverage from mapping table"
      - name: cross_system_alignment_score
        description: "Alignment score between CAD and Review systems"
      - name: account_mapping_status
        description: "Whether account is 'mapped_account' or 'unmapped_account'"
      - name: review_account_name
        description: "Name of linked review account (if mapped)"
      - name: review_account_id
        description: "ID of linked review account (if mapped)"

  - name: int_persona_gap_analysis
    description: "ENHANCED: Cross-account gap analysis with mapping insights - PRIMARY OUTPUT FOR DECISION MAKING"
    columns:
      - name: cad_account_id
        description: "CAD account identifier for analysis"
        tests:
          - not_null
      - name: persona_attribute
        description: "Normalized persona attribute"
        tests:
          - not_null
      - name: gap_priority
        description: "ENHANCED: Priority level (critical, high, medium, validation_needed, low)"
        tests:
          - not_null
          - accepted_values:
              values: ['critical', 'high', 'medium', 'validation_needed', 'low']
      - name: gap_type
        description: "ENHANCED: Type of gap (completely_unaddressed, underperforming, moderate_opportunity, well_served, ads_without_reviews)"
        tests:
          - not_null
      - name: recommendation
        description: "ENHANCED: Actionable recommendation with cross-system context"
        tests:
          - not_null
      - name: priority_score
        description: "ENHANCED: Numerical priority score with cross-account boost for ranking opportunities"
      - name: opportunity_level
        description: "ENHANCED: Opportunity level (critical_opportunity, high_opportunity, medium_opportunity_mapped, medium_opportunity, validation_needed, low_opportunity)"
      - name: review_count
        description: "Number of reviews mentioning this persona"
      - name: ad_count
        description: "Number of ads targeting this persona"
      - name: ad_account_name
        description: "CAD account name for context"
      - name: persona_coverage
        description: "Cross-system persona coverage type"
      - name: cross_system_alignment_score
        description: "Alignment score between CAD and Review systems"
      - name: account_mapping_status
        description: "Account mapping status (mapped_account, unmapped_account)"
      - name: review_account_name
        description: "Name of linked review account (if mapped)"
      - name: review_account_id
        description: "ID of linked review account (if mapped)"
      - name: cross_system_account_summary
        description: "Summary showing CAD ↔ Review account relationships"
      - name: priority_rank
        description: "Numerical rank for ordering (1=highest priority)"

  - name: int_persona_review_ranking
    description: "REPORT 1: Persona attributes ranked by review count - equivalent to source app's cluster ranking"
    columns:
      - name: persona_name
        description: "Persona attribute mentioned in reviews"
        tests:
          - not_null
      - name: account_name
        description: "Display name of the ad account"
      - name: ad_account_id
        description: "Ad account identifier"
      - name: review_count
        description: "Number of reviews mentioning this persona"
      - name: percentage
        description: "Percentage of total reviews that mention this persona"
      - name: total_unique_reviews
        description: "Total number of unique reviews analyzed"
      - name: volume_category
        description: "Volume classification: High/Medium/Low/Minimal Volume"
      - name: review_rank
        description: "Rank by review count (1 = most mentioned)"

  - name: int_persona_ad_performance
    description: "REPORT 2: Persona attributes ranked by ad spend with performance metrics (AOV, ROAS, Thumbstop)"
    columns:
      - name: persona_attribute
        description: "Persona attribute from ad analysis"
        tests:
          - not_null
      - name: ad_count
        description: "Number of ads targeting this persona"
      - name: total_ad_spend
        description: "Total advertising spend for this persona"
      - name: persona_mentions
        description: "Number of times this persona was mentioned in ads"
      - name: avg_confidence
        description: "Average confidence score for persona detection in ads"
      - name: aov
        description: "Average Order Value (total purchase value / total purchases)"
      - name: roas
        description: "Return on Ad Spend (total purchase value / total ad spend)"
      - name: thumbstop_rate
        description: "Video watch rate (3s+ video watches / impressions)"
      - name: total_purchase_value
        description: "Total purchase value generated"
      - name: total_purchases
        description: "Total number of purchases"
      - name: total_video_watches
        description: "Total 3-second video watches"
      - name: total_impressions
        description: "Total ad impressions"

  - name: int_persona_opportunity_index
    description: "REPORT 3: Opportunity Index analysis - calculates review_mentions / ad_spend ratio for persona prioritization"
    columns:
      - name: persona_attribute
        description: "Persona attribute analyzed"
        tests:
          - not_null
      - name: review_count
        description: "Number of reviews mentioning this persona"
      - name: review_percentage
        description: "Percentage of total reviews mentioning this persona"
      - name: ad_count
        description: "Number of ads targeting this persona"
      - name: total_ad_spend
        description: "Total ad spend for this persona"
      - name: raw_ratio
        description: "Raw opportunity ratio (review_count / ad_spend). 999999 = infinite (reviews but no ads)"
      - name: opportunity_index
        description: "Normalized opportunity score (0-100). Higher = better opportunity"
        tests:
          - not_null
      - name: opportunity_color
        description: "Color code for visualization (green = high opportunity, red = low opportunity)" 